-- ==========================================
-- Barbería La Chata - Esquema de Base de Datos
-- ==========================================

-- Enums para roles y estados de citas
CREATE TYPE user_role AS ENUM ('cliente', 'barbero');
CREATE TYPE cita_estado AS ENUM ('pendiente', 'aceptada', 'rechazada');

-- 1. Tabla de Perfiles (Se vincula con auth.users de Supabase)
CREATE TABLE perfiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    nombre TEXT NOT NULL,
    telefono TEXT,
    rol user_role DEFAULT 'cliente' NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Tabla de Servicios
CREATE TABLE cortes_servicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    precio NUMERIC(10, 2) NOT NULL,
    duracion_estimada INT NOT NULL, -- En minutos
    descripcion TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Tabla de Citas
CREATE TABLE citas (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    cliente_id UUID REFERENCES perfiles(id) ON DELETE CASCADE NOT NULL,
    barbero_id UUID REFERENCES perfiles(id) ON DELETE CASCADE NOT NULL,
    servicio_id BIGINT REFERENCES cortes_servicios(id) ON DELETE RESTRICT NOT NULL,
    fecha_hora TIMESTAMP WITH TIME ZONE NOT NULL,
    estado cita_estado DEFAULT 'pendiente' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Habilitar RLS (Row Level Security) en todas las tablas
ALTER TABLE perfiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE cortes_servicios ENABLE ROW LEVEL SECURITY;
ALTER TABLE citas ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- POLÍTICAS RLS (Row Level Security)
-- ==========================================

-- -----------------
-- Perfiles
-- -----------------
-- Cualquier usuario autenticado puede ver los perfiles (para seleccionar barbero en la reserva)
CREATE POLICY "Usuarios pueden ver todos los perfiles" 
ON perfiles FOR SELECT 
TO authenticated 
USING (true);

-- Solo el dueño del perfil puede actualizar sus propios datos
CREATE POLICY "Usuarios pueden editar su propio perfil" 
ON perfiles FOR UPDATE 
TO authenticated 
USING (auth.uid() = id);

-- -----------------
-- Servicios (cortes_servicios)
-- -----------------
-- Cualquiera (incluso visitantes no autenticados) puede ver el catálogo de servicios
CREATE POLICY "Cualquiera puede ver servicios" 
ON cortes_servicios FOR SELECT 
USING (true);

-- Solo usuarios con rol 'barbero' pueden crear, actualizar o eliminar servicios
CREATE POLICY "Solo barberos pueden modificar servicios" 
ON cortes_servicios FOR ALL 
TO authenticated 
USING (
    EXISTS (
        SELECT 1 FROM perfiles 
        WHERE perfiles.id = auth.uid() AND perfiles.rol = 'barbero'
    )
);

-- -----------------
-- Citas
-- -----------------
-- Los clientes ven sus propias citas y los barberos ven todas las citas de la barbería
CREATE POLICY "Clientes ven sus propias citas" 
ON citas FOR SELECT 
TO authenticated 
USING (
    auth.uid() = cliente_id 
    OR EXISTS (
        SELECT 1 FROM perfiles 
        WHERE perfiles.id = auth.uid() AND perfiles.rol = 'barbero'
    )
);

-- Los clientes pueden registrar sus propias citas
CREATE POLICY "Clientes pueden crear sus citas" 
ON citas FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = cliente_id);

-- Los barberos pueden modificar cualquier cita (para Aceptar/Rechazar) y el cliente puede modificar la suya propia (por ejemplo, para cancelar)
CREATE POLICY "Barberos y clientes modifican citas" 
ON citas FOR UPDATE 
TO authenticated 
USING (
    auth.uid() = cliente_id 
    OR EXISTS (
        SELECT 1 FROM perfiles 
        WHERE perfiles.id = auth.uid() AND perfiles.rol = 'barbero'
    )
);

-- ==========================================
-- TRIGGERS Y FUNCIONES AUTOMÁTICAS
-- ==========================================

-- Trigger automático para crear perfil cuando un usuario se registra en Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.perfiles (id, nombre, telefono, rol)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'nombre', 'Cliente Nuevo'), 
    new.raw_user_meta_data->>'telefono', 
    'cliente'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- DATOS SEMILLA PARA PRUEBAS RÁPIDAS
-- ==========================================
INSERT INTO cortes_servicios (nombre, precio, duracion_estimada, descripcion) VALUES
('Corte Premium + Lavado', 15.00, 30, 'Corte estilizado con asesoría de imagen, lavado con shampoo premium y acabado con pomada.'),
('Barba Esculpida & Ritual', 10.00, 25, 'Perfilado de barba con navaja libre, toalla caliente y aceites hidratantes.'),
('Combo La Chata (Corte + Barba)', 22.00, 50, 'El servicio completo de la casa. Incluye exfoliación facial rápida.');
